name: Run Android Tests on Remote Appium Server

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: |
          chmod +x ./gradlew
          ./gradlew test -Dappium.server.url=${{ secrets.APPIUM_REMOTE_URL }}